# Файл конфигурации Travis CI (лицензия MIT) для темы Underscores WordPress.
# @link https://travis-ci.org/

# Для использования с темой Underscores WordPress.
# @link https://github.com/Automattic/_s

# Скажите Travis CI, какую ОС и какой дистрибутив использовать.
os: linux
dist: xenial

# Кэширование каталогов между сборками.
# @link https://docs.travis-ci.com/user/caching/#arbitrary-directories
cache:
  directories:
    # Каталог кеша для npm.
    - $HOME/.npm
    # Каталог кеша для старых версий Composer.
    - $HOME/.composer/cache/files
    # Каталог кеша для более поздних версий Composer.
    - $HOME/.cache/composer/files

# Объявить язык проекта.
# @link https://docs.travis-ci.com/user/languages/php/
language:
  - php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: SNIFF=1

before_install:
  # Ускорьте время сборки, отключив Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  # Загрузите и установите последнюю версию долгосрочной поддержки узла.
  - if [[ "$SNIFF" == 1 ]]; then nvm install --lts; fi
  # Установите зависимости Composer.
  - composer install
  # Установите зависимости NPM.
  - if [[ "$SNIFF" == 1 ]]; then npm install; fi

script:
  # Проверьте файл composer.json.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict

  # Поиск синтаксических ошибок PHP с использованием PHP Parallel Lint.
  # @link https://github.com/php-parallel-lint/PHP-Parallel-Lint
  - composer lint:php

  # Проверьте файлы PHP со стандартами кодирования, описанными в файле phpcs.xml.dist.
  - if [[ "$SNIFF" == 1 ]]; then composer lint:wpcs; fi

  # Проверьте файлы JS с помощью скрипта lint-js, определенного в пакете @wordpress/scripts.
  - if [[ "$SNIFF" == 1 ]]; then npm run lint:js; fi

  # Проверьте файлы SCSS с помощью скрипта в lint-style, определенного в пакете @wordpress/scripts.
  - if [[ "$SNIFF" == 1 ]]; then npm run lint:scss; fi

# Получать уведомления о результатах сборки.
# @link https://docs.travis-ci.com/user/notifications/#configuring-email-notifications
notifications:
    email: false
